publishDir = "../docs"

baseURL = "/"
languageCode = "en-us"
title = "Balancer: Trustless Price Sensor and Portfolio Manager"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "API Reference"
    url = "/api/"
    weight = 1

[[menu.main]]
    name = "App"
    url = "https://app.balancer.finance"
    weight = 1

[params]
  google_analytics_id=""
  homepage_button_link = '/balancer.pdf'
  homepage_button_text = 'Read The Whitepaper'
  homepage_intro = 'Balancer: Trustless Price Sensor and Portfolio Manager'
  homepage_image = "https://balancer-labs.github.io/bb/bb.svg"

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Balancer: Trustless Price Sensor and Portfolio Manager"
    meta_og_title = "Balancer Protocol Documentation"
    meta_og_type = "website"
    meta_og_url = "https://github.com/balancer-labs"
    meta_og_image = "https://balancer-labs.github.io/bb/bb-mini.svg"
    meta_og_description = "Balancer: Trustless Price Sensor and Portfolio Manager"
    meta_twitter_card = "summary"
    meta_twitter_site = "@balancerpro"
    meta_twitter_creator = "@balancerpro"

  [params.logo]
      mobile = "https://balancer-labs.github.io/bb/bb-mini.svg"
      standard  = "https://balancer-labs.github.io/bb/bb-mini.svg"
